### ISSUE TITLE
Ghost Update error - current ghost version is 0.11.7

### ISSUE THREAD

**Issue by faizhameed** [TryGhost/Ghost-CLI#1069]
I get this error when I am trying to update Ghost.
npm version is 6.13.1
node version is 13.2.0
current ghost version
version 0.11.7

```
ubuntu@ip-172-26-6-152:/var/www/ghost$ ghost update
Ghost-CLI only works with Ghost versions >= 1.0.0.
```

**Comment by faizhameed** [comment]
Hi friends i didnt get a response yet why is this

**Comment by acburdine** [comment]
@faizhameed You're using Ghost 0.11.7, which means the error you're getting is intentional behavior, see https://github.com/TryGhost/Ghost-CLI#note-this-cli-is-not-designed-to-work-with-any-ghost-versions--100.

See the upgrade guide for how to update to the latest version of Ghost: https://ghost.org/update/?v=0.1
