### ISSUE TITLE
Add option to force ghost install

### ISSUE THREAD

**Issue by bermudalocket** [TryGhost/Ghost-CLI#1218]
### Summary

As a security precaution, `ghost` cannot be installed in a non-empty directory. This behavior is detrimental in at least one case. Consider a system utilizing `nodeenv` to manage multiple versions of NodeJS. If the system's global NodeJS version is set to 14.x, `ghost` cannot be installed due to version incompatibility. Creating a new directory for `ghost` and setting the local (directory) NodeJS version to 12.x via `nodeenv` creates a folder named `env`, which then blocks `ghost` from installing due to a non-empty directory.

Proposed solution is to add a `--force` flag to `ghost install`.

**Comment by acburdine** [comment]
@bermudalocket that approach makes sense - I'll work on adding that 👍

**Comment by ErisDS** [comment]
Sorry to throw a spanner in the works here, but whilst I agree that this report constitutes a genuine problem, I completely disagree that adding a `--force` flag is the correct solution.

1) because I had thought we already had code to ignore `.git` folders & that this could be added to that although I cannot find it now 🤔 

2) because we already have a `--force` flag in Ghost-CLI with a clear meaning.  `--force` is used to permit a re-run of a command that has already been run. Therefore, I would expect `ghost install --force` to specifically rerun a complete install in a directory where Ghost is already installed.

3) because we already have a flag pattern for skipping certain checks, e.g. `--no-check-mem` and so I would expect a flag that explicitly skipped a single check to follow this pattern, e.g. `--no-check-empty`.

When adding flags or commands, we have to consider how their name fits into the wider tool, in order to create a consistent toolset that's easy to work with and predict what will happen.

**Comment by vikaspotluri123** [comment]
> 1. because I had thought we already had code to ignore `.git` folders & that this could be added to that although I cannot find it now 🤔

Here's the line you're looking for:
https://github.com/TryGhost/Ghost-CLI/blob/4f7c80c885351dc59897b6297aac0b0e43690e4a/lib/utils/dir-is-empty.js#L13

I guess the issue is nodeenv creates a non-dot folder which is why the CLI was complaining. I totally see what you're saying about 2 and 3 😄

**Comment by acburdine** [comment]
Those points make sense, I’ll rename the flag 👍🏻

**Comment by bermudalocket** [comment]
As an end user unfamiliar with the inner workings of this project the semantics of the flag makes no difference to me. If there's a choice that better adapts to an existing naming scheme then that is obviously the better choice.

**Comment by straube** [comment]
I'm not sure if something changed after this issue was closed but it looks like the check empty defaults to `true` and is not possible to disable it. The `install` command always checks if the directory is empty, with or without the `--check-empty` option.
