### ISSUE TITLE
Ghost rootless

### ISSUE THREAD

**Issue by Bammede** [TryGhost/Ghost-CLI#1407]
### Issue Summary

Ubuntu 20.04 LTS server

Ghost is freezing after deploying by docker-compose on rootless docker.

from terminal:
Creating mysql ... done
Starting ghost ... done
Attaching to ghost ...... <and freezing, do nothing>

"docker logs ghost" shows nothing.

Checked config files and they seem to be ok.

### To Reproduce

1. Docker rootless
2. /etc/docker/daemon.json
{
        "data-root": "/mnt/docker-data",
        "storage-driver": "overlay2"
    },
    { 
        "userns-remap": "nonrootdockeruser"
    },
    {
        "live-restore": true
    },
    {
        "userland-proxy": false
    },
    {
        "no-new-privileges": true
    },
3.  run mysql docker-compose service
4.  run ghost docker-compose service

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

to run ghost cms

**Comment by acburdine** [comment]
@Bammede without your docker-compose file, I'm not sure how to help debug your issue.

Also, this issue is probably better put on the https://github.com/docker-library/ghost repo, since that's where the official docker image is maintained. As such, I'm going to close this issue. If we find that there's a bug in Ghost-CLI and _not_ in the docker image (or how you're using it) then we can re-open this issue 😄
