### ISSUE TITLE
Programmatic creation of admin user

### ISSUE THREAD

**Issue by yamsellem** [TryGhost/Ghost-CLI#1515]
Once installed, Ghost needs a proper admin user to start giving admin access (and api access). For now, the web interface is the only way to create such a user (at site/ghost url).

In the process of fully automate our Ghost install, we wish to script that creation too. We've found a workaround by inserting the admin user directly into mysql like this,

```
# xxx generated with htpasswd
USER_PASSWORD="xxx"
OWNER_ID=$(mysql -N --password="yyy" --database="ghost_prod" --execute="SELECT id FROM roles WHERE name='Owner';")

mysql -pyyy << EOF

INSERT INTO ghost_prod.users 
(id, name, slug, password, email, status, created_at, created_by)
VALUES
(2, "Full Name", "Surname", "$USER_PASSWORD", "email@mail.com", "active", "20210101", 1);

INSERT INTO ghost_prod.roles_users
(id, role_id, user_id)
VALUES
(2, '${OWNER_ID}', 2);

EOF
```

May you consider adding a `--ghostemail` and `--ghostpass` (or named otherwise) to the `ghost install` command so that email and password are used to create the first admin user?

Thanks a lot.

_ps. this question is [related to this one](https://forum.ghost.org/t/creating-admin-user-programmatically/8952) which as not been resolved yet_

**Comment by ErisDS** [comment]
I want to make very clear that the approach documented in this issue is dangerously wrong. Injecting data directly into the database puts Ghost into a completely unknown state. The correct approach is _always_ to use the API to insert data, so that all of Ghost's internal processes are able to run and ensure the data is in the right state.

Ghost creates the "owner" user when the database is populated on first boot. There must only be one owner user - violating that constraint invalidates Ghost's permissions layer meaning your site is probably completely insecure.

Once Ghost's DB has been initialised, there is a setup endpoint that needs to be hit - you can see all of this if you inspect the network tab whilst completing a standard setup via Ghost admin - and then reproduce it in a script.

---

I don't see any use case for adding flags like this - especially as for this to work the email and password would need to be stored somewhere, probably in plaintext, so that they can be read on boot - which is when the DB is populated.

IMO what you want to do is already possible using the API.

**Comment by yamsellem** [comment]
@ErisDS I completely understand that monkey-patching in Ghost database is wrong; we never want to go that way.

This being said, it seems to me that your answer to "always use the API to insert data" may have a blind spot: how one can call the API if no user exists in the system? Is the "owner" user created at first boot has an email / password that can be used to consume the API? Or another way of authentication maybe?

Is the web interface the only way to create the first "public" user (at site/ghost url) for now on?
Thanks a lot.

**Comment by vikaspotluri123** [comment]
> how one can call the API if no user exists in the system?

> Is the web interface the only way to create the first "public" user (at site/ghost url) for now on?

To answer both of these questions, anything that can be done in the web interface can be done using the API, because the web interface is "just" a wrapper around the API. The web interface does not have any special permissions which make it more privileged than an API consumer.

The easiest way to see what you have to do to get a new Ghost site set up is to install Ghost locally, and track the network requests (using your browser developer tools) as you go through the first run process.
