### ISSUE TITLE
Attempt to start new version of Ghost during `ghost update`

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#153]
The current update process works as follows:

- Download new Ghost version & install dependencies
- Stop current Ghost
- Update symlinks
- Start new Ghost

However, if an issue occurred during the installation of the new Ghost version, that issue won't be discovered until the blog is restarted, leaving your blog in an offline state. This is especially critical for automatic/one-click updates, as the user won't be running the update through the traditional means.

So the idea is to start the new version of Ghost on a different port temporarily _before_ stopping & starting Ghost. This should be fairly simple, and there is already a library (portfinder) in Ghost-CLI that can be used to find an open port.

However, this will involve some other thinking - namely how to start the new version of Ghost with the same content, _without_ messing with the current live database. With SQLite this should be pretty easy - just create a copy of the DB file, however if the user is using a MySQL database it might be a little trickier. Definitely needs some thought - as we don't want to just implicitly require that a sqlite database exist.

Kate Note: This is only related to one click updates!

**Comment by kirrg001** [comment]
Some thoughts on this.

First of all, we have to turn the current ghost blog into maintenance mode to avoid any updates to the database. We already have a maintenance flag in Ghost.

One problem with mysql could be that mysqldump is not available, because the executable is not correctly linked, but we could ignore that for the first version and tell the user why auto update wasn't working. Also, there are npm modules out there to dump and insert mysql database via javascript, e.g. https://github.com/webcaetano/mysqldump or https://www.npmjs.com/package/grunt-mysql-dump-import

Furthermore we have to override the database name/filename via env parameter if we start knex-migrator or if we start the new blog. 

If a migration happens and it fails, ghost-cli will know, because knex-migrator will fail.
If blog can't start, ghost-cli will know.

**Comment by acburdine** [comment]
That makes sense. I was thinking "trickier" along the lines of creating a new database might not work if the db user doesn't have the proper permissions. But what we could do in mysql is just dump the db and then try migrating-if that doesn't work then restore the old database from either the dump (if mysql) or the actual db file (if sqlite).
