### ISSUE TITLE
'ghost ls' does not show running secondary instance in subfolder after upgrade

### ISSUE THREAD

**Issue by piotrkundu** [TryGhost/Ghost-CLI#1535]
### Summary
I have two ghost instances running. Main blog is in folder "/srv/users/USER/apps/APPNAME/public" and secondary as a subfolder called "devnull" ("/srv/users/USER/apps/APPNAME/public/devnull"). I Upgraded from 3.42.5 to 4.12.1. Prior to this 'ghost ls' showed:
![image](https://user-images.githubusercontent.com/8414570/130114599-bb039040-d079-400d-a759-2192609e5afd.png)

### Steps to Reproduce
1. 'ghost ls'
![image](https://user-images.githubusercontent.com/8414570/130114860-6654b9da-dd28-4d19-8005-5441f1548b04.png)
'systemctl | grep ghost' clearly shows to instances running
Both blogs are running and working correctly

I'm using DigitalOcean and Serverpilot installed according to: https://brycematheson.io/how-to-update-ghost-on-digitalocean-managed-by-serverpilot/

### Technical details
* OS: Ubuntu 16.04
* Node Version: v12.22.5
* Ghost-CLI Version: 1.17.3

## Bug submission checklist

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [ ] Attached log file
- [ ] Provided technical details incl. operating system

**Comment by fultonm** [comment]
I had a similar problem where the ghost service was running but not showing with `ghost ls` and in my case it was because in `~/.ghost/config` the instance was using a `.` (dot). Changing this to a dash allowed the instance to show in `ghost ls`. Minor gotcha; don't know if that's going on for you.

It could help to post your `~/.ghost/config` and the `.ghost-cli` file in each ghost directory you are having problems with.
