### ISSUE TITLE
A SystemError occurred.

### ISSUE THREAD

**Issue by mysterybear** [TryGhost/Ghost-CLI#1539]
`ghost install local` says
```
✔ Checking system Node.js version - found v14.16.0
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v4.12.1
A SystemError occurred.

Message: Ghost v4.12.1 is not compatible with the current Node version.

Debug Information:
    OS: Arch Linux, vunknown
    Node Version: v14.16.0
    Ghost-CLI Version: 1.17.3
    Environment: development
    Command: 'ghost install local'

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```

`ghost doctor` says:

```
Run `ghost doctor` again within a folder where Ghost was installed with Ghost-CLI.
```

I'm on Archlinux. Am I being stupid? Not sure what to do next.

**Comment by acburdine** [comment]
@mysterybear Ghost bumped the minimum version requirements of Node to > v14.16.1 or > 12.22.1 due to a security vulnerability in earlier versions of node. If you update your version of nodejs to v14.16.1 or another newer Node 14 version, Ghost should work.

Alternatively, you can run `GHOST_NODE_VERSION_CHECK=false ghost install local`, which will disable the version check.

Closing this issue as this is intentional behavior in the CLI 😄
