### ISSUE TITLE
Current directory is not empty, Ghost cannot be installed here

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#173]
Could we optimise the validation for this error?

Here is the following case:
I run `ghost install help` and it fails because `help` is not available. There are for sure other command combinations users uses.

Then i run `ghost install` and it tells me that `Current directory is not empty, Ghost cannot be installed here.`. This is quite annoying, because the only file which was created is `ghost-cli-debug-2017-03-16T10.log`. And as none Ghost developer i might not know what todo. 

Possible tasks:
- [ ] improve messaging
- [ ] improve "Ghost cannot be installed here" validation

**Comment by dandv** [comment]
I still get this error incorrectly. It was triggered by entering the wrong password due to an arguably confusing prompt:

![image](https://user-images.githubusercontent.com/33569/37156636-710e6a32-229b-11e8-8e4c-6f9dfeb7ba0e.png)

After that, the installation seems to be in a broken state. I've deleted /var/www/ghost, but running `ghost install` produces "Message: Current directory is not empty, Ghost cannot be installed here.". Deleted `/var/www/` - no improvement.

**Comment by ErisDS** [comment]
@dandv I have questions:

>  triggered by entering the wrong password due to an arguably confusing prompt

What was confusing here? What were your expectations?

> After that, the installation seems to be in a broken state.

Did you try to use `ghost uninstall` ?

> I've deleted /var/www/ghost, but running ghost install produces "Message: Current directory is not empty, Ghost cannot be installed here.". Deleted /var/www/ - no improvement.

After deleting folders, where did you try to install Ghost? 

I understand that you expect that the CLI would clean up after itself, that's very tricky though - imagine if you ran `ghost install` in an already setup ghost folder by mistake, it failed, and Ghost deleted everything... it's better for us to err on the side of caution here.
