### ISSUE TITLE
Support setting install arguments using Environment Variables

### ISSUE THREAD

**Issue by Kamori** [TryGhost/Ghost-CLI#1742]
### Summary

Currently, if you attempt to install ghost programmatically you must use a command similar to the following.

`ghost install --no-prompt --url example.com --db mysql  --dbhost localhost --dbuser example_user --dbpass 'ExamplePassword123!@#'  --dbname example_database`

However, using passwords in cmd-line args is generally considered bad practice, especially if you're in any sort of shared environment. Simply running a `ps aux` while the above command is running means your password is exposed. It also means most config management tools will log that command in its entirety to its output or log files. This means we slowly start leaking those passwords in places we don't intend to.

My request is to support setting these variables via Environment Variables in addition to the `argv` inputs. 

unix based systems have a lot of support for different methods of loading environment variables. Commands like `DBPASS="secret" ghost install --no-prompt ...` would prevent the secret from being exposed in a `ps aux` output. But we can even go a step further and just source environment variables from a file with something like the following:

Assume a file named `~/.ghost_setup_vars` exists with the following contents:
```bash
export DBUSER="example_user"
export DBPASS="ExamplePassword123!@#"
```

We can then simply do the following:
```bash
source ~/.ghost_setup_vars && ghost install --no-prompt
```
Then so long as we delete that file after we're done, we avoid any additional secret leakage.

--
I think implementing this could also open up an avenue to improve #721. If we could set something like `SUDO_PASSWORD` as an environment variable, ghost-cli can just use that password for sudo prompts. This avoids the previously recommended path of creating a passwordless sudo which is effectively the same as just running ghost-cli as root.

I'd appreciate any effort that could be put into implementing this. It would greatly help my scenario.

**Comment by KurtWagner** [comment]
It looks like Ghost CLI uses [Yargs](https://yargs.js.org) for command line arg parsing, which appears to support an [environment prefix option](https://yargs.js.org/docs/#api-reference-envprefix). So this may be as simple as updating the [base Command class](https://github.com/TryGhost/Ghost-CLI/blob/main/lib/command.js#L78) to configure an environment prefix (e.g., `yargs.env('GHOST_CLI')`) so that you can invoke the CLI like

* `GHOST_CLI_URL=hostname.com ghost install ...` or
* `ghost install --url=hostname.com ...`

Another option could be to support file input for sensitive arguments - given there's still some risk to leaking environment variables (maybe more so when using `source my_secrets && ghost ...` with `export` instead of `DBPASS=123 ghost ...`?).

Yargs has a [config file option](https://yargs.js.org/docs/#api-reference-configobject) but I'm not sure it would be that wise storing secrets in structured data alongside non-sensitive data (easy to accidentally commit/share?) so maybe better as a separate plain file path?
