### ISSUE TITLE
feature request: set multiple configuration values via 'ghost config'

### ISSUE THREAD

**Issue by peterhuene** [TryGhost/Ghost-CLI#204]
Currently `ghost config` accepts a single key-value pair to write to the configuration file.  It would be nice if multiple values could be specified such that only a single execution of `ghost config` could, essentially, create a complete config file from scratch.

**Comment by acburdine** [comment]
@peterhuene definitely seems like a good idea - one thing you can do at the moment is specify (almost) all the necessary configuration values by passing them as command line options: https://github.com/TryGhost/Ghost-CLI/wiki/Command-Reference#ghost-config

So you can run `ghost config --dbname=x --port=1234` .. etc and it will essentially accomplish the same thing. My opinion is that doing it via command line flags is a bit better, especially because some of the config values are nested (e.g. the actual config location of `port` is `server.port`, database configurations are nested, etc).

Will keep this open though, if using command line flags doesn't work then I can work on adding support for it 😄

**Comment by peterhuene** [comment]
Hi @acburdine.  Thanks for the suggestion; while that definitely does work, there are some settings that don't have corresponding command line options to `ghost config`, such as the `mail` options.  

Some context: I'm working on a Docker image and Kubernetes Helm chart to package Ghost for ARMv7 (Raspberry Pi 3 in my case).  The Docker image configures Ghost upon first run if the volume is missing configuration.  Right now I'm using a Bash heredoc to write a complete JSON file out, but I'd like to use `ghost config` so that the script isn't reliant on the configuration file format.

Thanks again for the help!

**Comment by acburdine** [comment]
@peterhuene just out of curiosity, does the newer version of the CLI (1.0.2) have enough command line arguments to get mail settings working correctly? A lot were added, and I feel like if people have the need to edit multiple configuration values at once then we're likely missing some needed command line options.

**Comment by ErisDS** [comment]
It is working for me for creating mailgun setups. 

I think `ghost config key value` is a nice special case, for example for setting url, but that `ghost config --flag=value --flag2=value` makes sense for the case of multiple keys and values.

I've used it extensively since I implemented it 😬

**Comment by peterhuene** [comment]
@acburdine I haven't had a chance to give it a try, but I will soon.  I'll close this out for now and I'll reopen if I run into any issues.

Thanks very much!
