### ISSUE TITLE
Default log file

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost-CLI#219]
There seems to be incorrect time in filename of ghost-cli log. From my point of view it would be much better to have single log file by default without time and date in filename. You may also consider moving log files by default to standard log path eg.: `/var/log/ghost/<pname>.log`.

```
[ghost@strefadyskomfortu strefadysk_prd]$ date
Wed Jun 21 16:52:29 CEST 2017
[ghost@strefadyskomfortu strefadysk_prd]$ ls ghost*
ls: cannot access ghost*: No such file or directory
[ghost@strefadyskomfortu strefadysk_prd]$ ghost start
 ✔ Validating config
An error occurred.
Message: 'Ghost is already running.'


Debug Information:
    Node Version: v6.11.0
    Ghost-CLI Version: 1.0.0-alpha.18
    Environment: production
    Command: 'ghost start'
[ghost@strefadyskomfortu strefadysk_prd]$ ls ghost*
**ghost-cli-debug-2017-06-21T14:52:44.524Z.log**
[ghost@strefadyskomfortu strefadysk_prd]$ date
Wed Jun 21 16:53:11 CEST 2017
```

Ghost Version: beta.1
OS: Centos 7.3
Database: MariaDB

**Comment by rv-aburdine** [comment]
@PaszaVonPomiot Not sure why the date is off - it might be because the date ghost-cli uses is in UTC?

As far as logging goes, I definitely think the date/time should be kept in if only for ordering, especially if the logs are moved to a central place (which is being considered). I would say, though, that the log location should be user-specific and not in `/var/log`, mainly because ghost-cli only outputs logs if something goes wrong.

**Comment by PaszaVonPomiot** [comment]
I use UTC+1 timezone and the hour in filename is shifted by 2h. But that's low priority issue.
