### ISSUE TITLE
Nginx config client_max_body_size

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#231]
Nginx defaults to a max body size of 1mb, which isn't great for image and theme uploads.

I have been adding `client_max_body_size 50m;` as part of the install process for nginx before running ghost-cli.

On a fresh nginx install, I do this by adding the line after `types_hash_max_size 2048;` in /etc/nginx/nginx.conf. Ansible has a lovely tool called "lineinfile" that I wonder if we can reproduce?

I wonder if we should either document this, or get ghost-cli to attempt to set it?

**Comment by acburdine** [comment]
Something that might be possible to add to the nginx configuration setup is something with command args - e.g. `--nginx_client_max_body_size "50m"` will add that rule to the nginx config.

Since yargs doesn't throw on extraneous args we should be able to do something like this for various nginx rules.

**Comment by acburdine** [comment]
Apologies - should have made that a bit more clear 😬 

Definitely agree with adding the max_body_size config rule. The command line args thing would work for other use-cases of adding special rules on a per-conf bases.

**Comment by kirrg001** [comment]
I have referenced this issue in the improvements section in #216.
