### ISSUE TITLE
Use Ignition errors

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost-CLI#239]
I saw that the CLI has a custom implementation of errors, see https://github.com/TryGhost/Ghost-CLI/blob/master/lib/errors.js.

In my opinion there is no need to implement a custom error solution here. Ignition offers a full error solution. The CLI is already using Ignition as dependency to inject the PrettyStreamer.

**Comment by acburdine** [comment]
@kirrg001 I definitely thought about using Ignition errors when I needed to inject the PrettyStreamer. However the errors in Igntion cover a whole bunch of cases that the CLI _doesn't_ need to cover, and vice versa. The CLI doesn't have the concept of anything like a status code, or any need to render the error as JSON. Conversely, Ignition doesn't have any error handling to pull data from child processes, or render helpful errors such as the CLI's ConfigError does.

Ultimately, I _could_ make the errors extend from IgnitionError rather than Error, but at that point I'd be reimplementing a lot of errors anyways so I thought it best to not have _another_ file require, esp. when memory usage (of `ghost run` in particular) is a concern.

**Comment by acburdine** [comment]
Also should have mentioned - it's possible to extract the error handling from the CLI into Ignition, however imo the errors in Ignition are better suited for http server applications, while the CLI's errors are for different use-cases, so putting the CLI's errors in Ignition is not worth it for the 1 time they'll be used.
