### ISSUE TITLE
Local Process Manager shouldn't error if process not found

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#241]
The local process manager uses [fkill](https://npmjs.com/package/fkill) to handle killing of the Ghost process. When it was first built, a check was programmed in to not throw an error if the process didn't exist.

Somewhere in dependency updates the format of the error message returned from fkill was changed, so we need to update [this line](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/services/process/local.js#L64) to handle the new error format.

**Comment by acburdine** [comment]
Update: After some investigation the error message format _hasn't_ changed - it might be something to do with the operating system. On Mac the error message is correct, but on linux it's probably different.

**Comment by acburdine** [comment]
Looking into this further plus dialogue with some on Slack seems to point this to a problem with the user not being able to stop processes (e.g. in a docker container). Going to leave this open, but moving it to a post-1.0 issue as I think it's ok for the time being.

If it gets reported more, then this can be made a priority again.

**Comment by acburdine** [comment]
Going to close this for now - even if the error messages are different the 'is running' feature of the process managers should have fixed this. I tested on different systems and couldn't get this issue to re-occur as it's been reported by others on slack. If this issue occurs more then it can be re-opened.

**Comment by badrihippo** [comment]
@acburdine looks like I've run into this error again on Ubuntu! When ghost is force-closed, then next time it reopens it fails with uncaught exception "Process doesn't exist". It's because Ghost expects it to be framed as "No such process" instead.

I fixed by changing a line in [lib/utils/local-process.js](https://github.com/TryGhost/Ghost-CLI/blob/c9299c8f5617708a40bfedfa95089c01ecc3f5cb/lib/utils/local-process.js#L107):

                // TODO: verify windows outputs same error message as mac/linux
                if (!error.message.match(/No such process/)) {

becomes

                // TODO: verify windows outputs same error message as mac/linux
                if (!error.message.match(/No such process|Process doesn't exist/)) {

Not sure if this is specific to my setup (Ubuntu 18.04 Bionic) or generic to all/many Linux/Unix machines. Should it be looked into?
