### ISSUE TITLE
--quiet results in enable/disable being skipped

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#335]
The start and stop commands both have a `--quiet` flag.

This flag prevents the UI from outputting anything on start/stop, but also prevents the enable/disable step from happening.

I am not sure what the intention of the `--quiet` flag is. It only appears in a handful of places, was it a precursor to `--no-prompt`? 

@acburdine if you can clarify the intention here, I think I can fix/remove this. It's totally non-urgent except in that I am going to be removing the quiet flag when passed to `stop` from `uninstall` so that the systemd disable command is run on `uninstall`.

**Comment by acburdine** [comment]
so it's not an official flag actually, I added it in there so that the start/stop commands, when called programmatically from something like `ghost update`/`ghost uninstall`, wouldn't log anything out as it would mess up the listr flow.

Not as consequential now that `ghost restart` doesn't actually use `start` & `stop`, so am 👍  for any changes that you want to make, just need to double check that whatever solution still works correctly with `ghost update` as well as `ghost uninstall`, as those are the two places where stop is called programmatically.

**Comment by ErisDS** [comment]
Yeah, now that I've removed it, I see I get "Stopping Ghost" output twice, so can see what it was meant to do...

**Comment by acburdine** [comment]
there _should_ be a better way to go about this - maybe adding a second property to the `run` method in the stop command?

**Comment by ErisDS** [comment]
I've had a go 😁
