### ISSUE TITLE
Ghost-CLI version inconsistency

### ISSUE THREAD

**Issue by PaszaVonPomiot** [TryGhost/Ghost-CLI#359]
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary
Just found some inconsistency in `ghost version` and `.ghost-cli` file. Not sure if it's important.

```
[ghost@strefadysk strefadysk_prd]$ cat .ghost-cli
{
  "cli-version": "1.0.0-beta.6",
  "active-version": "1.0.0-rc.1",
  "name": "strefadysk_prd",
  "extension": {
    "systemd": true
  },
  "previous-version": "1.0.0-beta.2",
  "running": "production"
}
[ghost@strefadysk strefadysk_prd]$ ghost version
Ghost-CLI version: 1.0.0-rc.2
Ghost Version (at /var/www/strefadysk_prd): 1.0.0-rc.1
```

### Steps to Reproduce (for a bug report)

1. install ghost blog
2. update ghost-cli to latest version

**Comment by acburdine** [comment]
This isn't an inconsistency - the version in the .ghost-cli file is the one that the install was created with. It was put there so that if we ever have to change the install structure and perform some sort of migration, then we know what structure the original install was created with based on the cli version.
