### ISSUE TITLE
Ghost having stopped status while running after machine reboot

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost-CLI#431]
This happens to me after **I executed `ghost stop` in my ghost install folder** and **rebooted my machine**.

Steps:
* I have executed `ghost stop`

* Then I have executed `reboot`

* After the machine boots up and after a few seconds, I tried to access the domain and the **site loads**. 😕 

* Then I have executed `ghost ls` and I found this:
![image](https://user-images.githubusercontent.com/9730242/28989990-c1d38c7a-79ab-11e7-8e6b-aba6608b66e2.png)
The second ghost is live despite having a `Stopped` status. And when I try to execute `ghost stop`, it just reports that ghost isn't running. 😕

**Comment by acburdine** [comment]
So I know what causes this - need to think a bit on how exactly to resolve it.

The reason this occurs is because Ghost-CLI puts a little "running" property in the `.ghost-cli` file whenever it's started -> this is used so that the CLI can determine what environment Ghost is running in (e.g. dev/prod). What's happening is that `ghost stop` is removing that `running` property from the `.ghost-cli` file, but systemd is restarting it on reboot. `ghost ls` looks for that running flag to determine if Ghost is running, so it's saying `stopped` because the running flag is no longer present.

My initial thought is to expand the `running` flag a bit - have `ghost run` set it rather than `ghost start`, but it needs some more consideration.

**Comment by yaccin** [comment]
I think the issue rather is that systemd can't enable the ghost services because they are links:

systemctl enable ghost-blog.service Failed to execute operation: Too many levels of symbolic links

https://github.com/systemd/systemd/issues/3010

**Comment by acburdine** [comment]
@yaccin that is a separate issue - enabling _should_ work fine on Ubuntu 16

**Comment by yaccin** [comment]
I am on 16.04 and i can't enable the services. In addition, after the restart (kernel update) i now am also getting

Failed to start ghost_geeks-lgbt.service: Unit ghost_geeks-lgbt.service not found.
✖ Starting Ghost
A ProcessError occurred.

Error occurred running command: '/bin/sh -c sudo systemctl start ghost_geeks-lgbt'

Exit code: 5


Debug Information:
    Node Version: v6.11.2
    Ghost-CLI Version: 1.0.3
    Environment: production
    Command: 'ghost start'


when trying to start ghost manually

**Comment by YOnoda** [comment]
Has this been not fixed yet? I could nither stop nor restart Ghost since it is running yet is shown not...

**Comment by acburdine** [comment]
@YOnoda I'm sorry for not getting this fixed yet - it's definitely on my radar, I just need to find the time to finish implementing the fix :)

**Comment by n-kolodziej** [comment]
Is there an ETA for this fix? Still cannot restart my Ghost instance.

**Comment by arjunmayilvaganan** [comment]
Is there a temporary work around for this? I thought of killing the `node` process & starting the instance via `ghost`.
But, even if the `node` server is `kill`ed, it seems to be getting back up again.

**Comment by acburdine** [comment]
Closed via #607
