### ISSUE TITLE
Node 8 Support

### ISSUE THREAD

**Issue by hpohlmeyer** [TryGhost/Ghost-CLI#462]
### This issue is a

* [ ] Bug Report
* [x] Feature Request

### Summary

`ghost install local` fails with this error:

```
A SystemError occurred.

Message: The version of Node.js you are using is not supported.
Supported: ^4.5.0 || ^6.5.0
Installed: 8.4.0
```

Since Node 8 is the current version and the next LTS version, support for it would be nice.

### Steps to Reproduce (for a bug report)

1. Run `ghost install local`

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* Node Version: 8.4.0
* Ghost-CLI Version: 1.1.1
* Environment: development
* Command: `ghost install local`

**Comment by sebgie** [comment]
Hey @hpohlmeyer! There is writeup about how Ghost handles Node versions: https://docs.ghost.org/v1.0.0/docs/supported-node-versions.

@acburdine Would it make sense to include the link in the error message? I'm not sure atm if it comes from Ghost-CLI or Ghost itself 🙈 .

**Comment by hpohlmeyer** [comment]
@sebgie Ah okay, so Node 8 support will start in October.  
Still, I am wondering why you wait for the LTS phase instead of supporting the current version. Are you waiting until it is feature-complete to minimize issues? Not a critique – just curious. :)

Regarding the error message: I think including a link would be nice.

**Comment by kevinansfield** [comment]
> Still, I am wondering why you wait for the LTS phase instead of supporting the current version. Are you waiting until it is feature-complete to minimize issues? Not a critique – just curious. :)

@hpohlmeyer hopefully that is answered in that doc https://docs.ghost.org/v1.0.0/docs/supported-node-versions#section-why-follow-lts-

> Regarding the error message: I think including a link would be nice.

The link should already be there, perhaps it was just omitted from the copied error?
https://github.com/TryGhost/Ghost-CLI/blob/b34810580c6c14fa2b632501f7d100b581b42b8a/lib/commands/doctor/checks/install.js#L53-L57

Closing this because Node.js 8 support will be added when it becomes LTS as per our Node.js version support policy. If you can re-produce the missing link to the supported versions doc please open a separate issue, thanks 😄
