### ISSUE TITLE
Ghost-Cli Error install on Debian

### ISSUE THREAD

**Issue by greg5678** [TryGhost/Ghost-CLI#464]
I was trying to install Ghost via the ghost-cli. Here is the error log. 
`Debug Information:`
    `Node Version: v6.11.2`
    `Ghost-CLI Version: 1.1.1`
    `Environment: production`
    `Command: 'ghost install'`
`An error occurred.`
`Message: Command failed: /bin/sh -c sudo -E -u ghost /usr/lib/nodejs/node-v6.1$`
`/usr/bin/env: node: No such file or directory`

`Stack: Error: Command failed: /bin/sh -c sudo -E -u ghost /usr/lib/nodejs/node-$`
`/usr/bin/env: node: No such file or directory`

    at Promise.all.then.arr (/usr/lib/nodejs/node-v6.11.2/lib/node_modules/ghos$
    at process._tickCallback (internal/process/next_tick.js:109:7)
`Code: 127`

I don't have an env directory in /usr/bin.

**Comment by acburdine** [comment]
@greg5678 sorry for taking a while to get to this!

My guess is there's something wrong with how you installed node - would you mind giving some info about how you installed node on debian?

(Note: the recommended way to install it on ubuntu and debian is to use node's PPA -
 see docs here: https://nodejs.org/en/download/package-manager/)

**Comment by acburdine** [comment]
@greg5678 after talking with several in slack that seem to have had this same issue, it turns out that if you just run `apt-get install nodejs`, it will install the binary as `nodejs` rather than just `node`, which is what is causing this step to fail.

If you install node using the official recommended way (see the link in the previous comment), then it should work fine. If it turns out that it doesn't and there is a reproduceable issue with the CLI then we can reopen this 😄
