### ISSUE TITLE
Give sysadmins ability to run privileged commands themselves

### ISSUE THREAD

**Issue by TheCapsLock** [TryGhost/Ghost-CLI#475]
### This issue is a

* [ ] Bug Report
* [X] Feature Request

### Summary

as a system administrator, I'm not confident to let a program run privileged commands at root level.

This feature request is all about giving system administrators ability to 

* run sudo commands manually in place of ghost-cli (this could be accomplished by prompting sysadmin what to do (eg systemctl stop ghost) and wait for hir to tell ghost-cli it has been done
* add an option to ghost-cli to tell it what commands can be run with sudo (by specifying command path : so we can add an entry to /etc/sudoers to let ghost-cli run this command

If this is a feature request, use this section to describe what feature you would like to see in the CLI, as well as a quick summary of any benefits or drawbacks you can think of if this feature is implemented.

**Comment by acburdine** [comment]
@TheCapsLock I understand where you're coming from - however I think the feature as you've described it would likely cause more confusion and breakage, mainly because commands often have additional things that they require other than just the raw command itself; for instance, various environment variables. Also, if say the sysadmin mistyped a command, then the CLI would potentially have issues :/ The other problem with making the CLI output a list of commands that it needs sudo for is that that list can change somewhat depending on context - if you skip the nginx setup then you don't need those commands, if you don't use systemd then you don't need those commands, etc. It's not easy for the CLI to simply _know_ what sudo commands it needs to run without being in the middle of the setup process.

I've got an idea though that might be a good compromise. Currently, the CLI outputs the sudo command it's running to the console right before it runs the command. What if a flag were added that, if provided to the CLI, would pause the CLI's execution after outputting the sudo command being run, and ask the sysadmin for confirmation. The sysadmin wouldn't run the command manually, but the CLI would wait until said person gave it the permission to run the sudo command. This would also potentially give the sysadmin time to add the needed command to the sudoers file _before_ the CLI tries to run it.

Here's an example flow (wording subject to change):

Before a sudo command is run:
```
# various other setup output here
Running sudo command: systemctl start ghost_myblog.com
Is it okay for the CLI to run this command? (Y/n): 
```

After permission was given:
```
# various other setup output here
Running sudo command: systemctl start ghost_myblog.com
Is it okay for the CLI to run this command? (Y/n): yes
✔️ Starting Ghost
```

The only problem with this approach is if you said "no" to giving the CLI permission, your Ghost install would be in a broken state, and the CLI wouldn't necessarily know how to fix it.

**Comment by ErisDS** [comment]
As a sys admin, you can choose to run `ghost install --no-setup` and handle everything else yourself. Therefore there is already an option in place if you don't want the cli running those tasks.

> The only problem with this approach is if you said "no" to giving the CLI permission, your Ghost install would be in a broken state, and the CLI wouldn't necessarily know how to fix it.

And that is, fundamentally, the crux of it. If you give people the option to say no then people will get themselves into situations that require support.

The point of Ghost CLI is twofold: 
1. improve the ease of installing and upgrading Ghost 
2. reduce the support burden on the Ghost project

This feature request doesn't help with either of those goals, but does have an available workaround and therefore I feel strongly that this should be closed.

**Comment by TheCapsLock** [comment]
@acburdine the idea you expressed is exactly what I had in mind.
@ErisDS just printing what ghost CLI is going to run with sudo is not satisfying when focusing on host security

**Comment by ErisDS** [comment]
@TheCapsLock you misunderstand me. If you run `ghost install --no-setup` then the CLI will install Ghost, but not run any of the supplementary system setup steps that require sudo. 

The default setup steps exist to help the majority of users who would struggle to configure their server alone. Users such as yourself who are security-conscious sysadmins should be reading the docs, using `--no-setup` and doing your own configuration.
