### ISSUE TITLE
Default database name

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#508]
Tiny note, not important right now.

If I hit enter when doing a production install, the database name ends up being `ghost_production_ghost`.

Really don't want to have to type that beast out forever more.

`ghost`, `ghost_prod`, or `ghostdb` or similar would suffice?

**Comment by TomChantler** [comment]
Well the database name is now deliberately `ghost_environment_foldername` where you are (generally) installing into `/var/www/foldername`. It needs to be unique for each installation otherwise it goes wrong as described in #453 and fixed in #454. 

So `ghostdb` would not suffice. I suppose it might be possible to shorten it, but the current naming convention tells us it's a ghost database, that it's the production version (there may be a dev version) and to which installation it pertains. I think we need all of this information and I can't really think of a better way of doing it. Can you?

**Comment by acburdine** [comment]
As suggested by @vikaspotluri123 -> a better way to do this is: `<foldername>_environment` -> I think it's clear enough as to what exactly it is. If people use `/var/www/ghost` as the folder then I think it works. Will get working on fixing this.

**Comment by ErisDS** [comment]
Can we use abbreviated env names for prod & dev, so if my folder is `ghost` I get `ghost_prod` not `ghost_production` :D
