### ISSUE TITLE
Update notifications for Ghost-CLI

### ISSUE THREAD

**Issue by acburdine** [TryGhost/Ghost-CLI#525]
Related to #505, TryGhost/Ghost#9199, #495 

Currently we have an issue in the CLI in that there is no serious prompting to upgrade the CLI itself. There is currently an upgrade notification, but that happens _after_ a ghost command is run, and doesn't specify that it is a _required_ upgrade, just that there is a new version available.

We need to implement a way to either require or strongly suggest that a user update the version of Ghost-CLI. There are two scenarios in which I think this is required:

1. A critical bugfix in the CLI itself, unrelated to changes in Ghost. (example: #495)

In this situation, an issue was discovered with the nginx setup, and a fix was released in 1.2.0. However, people would not get that fix unless they updated to the latest version of the CLI. We need to be able to tell these users that they need to upgrade in order to get these fixes.

2. A breaking change in Ghost itself that requires a CLI update. (example, TryGhost/Ghost#9199)

In this scenario, Ghost is changing the migration files themselves due to breaking changes in the knex-migrator dependency. Because the current version of the CLI depends on an old version of knex-migrator, we would need to prompt the user to update Ghost-CLI prior to installing the new version of Ghost.

There are two checks that we can add to fix these issues:

1. Check for a new Ghost-CLI version when `any` ghost command is run, and require the user to either update first, or continue without updating. Something like this:

```sh
$ ghost update # or ghost ls, ghost install, etc
Warning: a new version of Ghost-CLI is available that contains some important fixes.
You should update your CLI version before running this command.
(Run `npm install -g ghost-cli@latest` to update)
Continue anyways? [y/N]:
```

2. Add a semver range in the package.json of Ghost itself that specifies what versions of the CLI it is compatible with.

Ghost-CLI would check this prior to actually downloading & updating to the latest version of Ghost. If the current CLI version is older than the version that Ghost's package.json says its compatible with, it will error out with a message saying ghost-cli needs to be updated.

**Comment by kirrg001** [comment]
Some additions:

If we add the CLI version checks explained above, we remove the knex-migrator dependency from the CLI (see #505) and release a new version, then we could publish a tiny blog post that people should update their CLI to the latest, otherwise they can run into problems. 

---

We won't add any backwards compatible changes to knex-migrator v3 - if you don't update your CLI and ignore release notes or the blog post, you could run into problems. We will add any possible error messages into our troubleshooting section on docs.ghost.org. Furthermore i'll do some more testing later if your database could be in bad state if you run the CLI with knex-migrator v2 using Ghost's adapted knex-migrator v3 scripts and you receive an error e.g. syntax error. 

---

Is it on purpose that #495 was closed?
