### ISSUE TITLE
[BUG] updateCheck disallow non-interactive setup 

### ISSUE THREAD

**Issue by silviofdez** [TryGhost/Ghost-CLI#563]
https://github.com/TryGhost/Ghost-CLI/blob/ff5e4ad9c30e75a10134741f96de31642123bce8/bin/ghost#L14

From ghot-cli 1.3.0 on wards, there is no way to proceed with unattended installations (`--no-prompt`) when a newer version of ghos-cli is detected. It could be useful in some circumstances but, under different ones, it should be avoidable.

I.E. when trying to install you need to pass `ghost` a lot of parameters if using in a non-interactive way `setup ........` but it becomes interactive because `inquirer` launch a question after the `updateCheck`. This is not consistent.

Related: https://github.com/TryGhost/Ghost-CLI/issues/525

**Comment by acburdine** [comment]
Closed by #566

**Comment by tianon** [comment]
Ran into this same issue with the latest release -- Docker official image builds of `ghost` started failing due to this prompt being displayed even in the non-TTY case (where stdin is even closed, which is the only reason it fails instead of simply hanging AFAICT).

In digging in the code, I found that this prompt is always enabled for the subcommands which #566 limited it to (regardless of the value of the `--prompt` flag, as @silviofdez has noted above).

We do plan to update `ghost-cli` in the images, but it'd be nice if we didn't have all the old images start failing to build immediately in the interim, especially since our `Dockerfile` is already hard-locked to both a specific version of Ghost-CLI _and_ Ghost, so we should be getting the same experience every time both before and after a new version of Ghost-CLI is released.  I'd thus respectfully request that this issue be reopened with a proposed fix being a method for either disabling this check or turning it into a warning instead. :pray: :heart:

**Comment by acburdine** [comment]
@tianon that’s a fair point - I’ll push a new fix. Sorry for the trouble!

**Comment by tianon** [comment]
Thanks @acburdine, you're a hero! :heart:

**Comment by acburdine** [comment]
@tianon apologies for the delay - I'll get a version out with this fix later today :)

**Comment by acburdine** [comment]
@tianon The new version has been published as 1.4.2. The docker builds will probably break for this release (because the 1.4.1 version still contains the issue), but after fixing it this time the builds shouldn't break again. Sorry for the trouble!

**Comment by tianon** [comment]
Amazing, thanks so much @acburdine!! :heart: :heart:
