### ISSUE TITLE
Why is sudo used in the uninstall command?

### ISSUE THREAD

**Issue by travismiller** [TryGhost/Ghost-CLI#577]
This makes it not possible to automate uninstall if the user does not have or need sudo.

If it is necessary, should there be a option to not use sudo? `ghost uninstall --no-sudo`

https://github.com/TryGhost/Ghost-CLI/blob/dd5d224f7fdf20c05346c0e6761145bed9c8e0fe/lib/commands/uninstall.js#L46-L48

**Comment by acburdine** [comment]
The reason sudo is used is because, by default in production, an additional `ghost` user is created to run the Ghost server process. That user is then made owner of the content folder. Hence during uninstall, sudo is required to remove that content folder.

I can update that check there to also check if the content folder is actually _owned_ by the ghost user, but if it is owned by the ghost user there's no way to run `uninstall` completely without sudo.

What, specifically, is your use case for automating uninstalls?

**Comment by acburdine** [comment]
@travismiller ^

**Comment by travismiller** [comment]
@acburdine thanks for the clarification!

Using sudo in the default case (production) makes sense to me. Though, I do prefer your idea of detecting the ownership of the directory as a condition of using sudo.

Our use case is not well defined, but we're experimenting with a developer kit for developing multiple Ghost projects. Our developers would all be `darwin` and would not encounter this anyway.

FWIW, here's some throw away code I wrote while exploring the issue that compares ownership. https://github.com/broco1974/Ghost-CLI/commit/06fe197e6b47dad3099018524747ba815c6b9c58

**Comment by acburdine** [comment]
Makes sense.
