### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by PhoenixPeca** [TryGhost/Ghost-CLI#652]
I can't seem to proceed in updating my ghost instance because the update procedure asks for my root password even though I am trying to input the right password.
![image](https://user-images.githubusercontent.com/9730242/36361522-a49b0496-1567-11e8-912b-d7ef54d5975f.png)

**Comment by vikaspotluri123** [comment]
Hey 👋 what user are you running as? It looks like you're runnning as `ghost` which is the system user that *only* runs ghost; you should be using a separate user to manage ghost instances.

**Comment by PhoenixPeca** [comment]
Looks like i havent added the user as one of the sudoers. so, my bad.. im closing this now

**Comment by vikaspotluri123** [comment]
Alright, but if this is the user that's running ghost, it _shouldn't_ be in the sudoers group!

**Comment by PhoenixPeca** [comment]
ok, i got it. gotta change my setup then. 😁😁

**Comment by vikaspotluri123** [comment]
Feel free to reach out on [slack](https://slack.ghost.org) if you have any questions!

**Comment by kirrg001** [comment]
@AileenCGN Shouldn't `ghost doctor` catch this case before updating?

**Comment by AileenCGN** [comment]
This should be checked by #47

**Comment by vikaspotluri123** [comment]
I think there are 2 issues at play here - the first is using the ghost user to run commands, and the second is the inability to create the home directory. The first issue is definitely something that could be checked with doctor, but the second happens when the System class attempts to create the global config ([here](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/system.js#L67)) to store the instance information

**Comment by AileenCGN** [comment]
> The first issue is definitely something that could be checked with doctor

Agreed. That is exactly the thing that we should check. We could improve the `check-root-user` fn to also check if the current user is logged in as a ghost user somehow and prevent running commands as it.

> the second happens when the System class attempts to create the global config

We wouldn't actually get to this step if we stop the process because of the first issue already, correct? Nevertheless this part definitely needs some error handling, which I'm currently tackling with #587

**Comment by vikaspotluri123** [comment]
> We wouldn't actually get to this step if we stop the process because of the first issue already, correct? 

I was actually thinking along the lines of not creating the user properly. I know in one of the VMs I used to have I used `useradd` instead of `adduser` which didn't create the homedir (`adduser` is a pretty wrapper for `useradd` and takes care of things like that) which in turn would have theoretically created the same issue for me. The only question is how often would something like this happen / is it worth adding a catch block to the codebase
