### ISSUE TITLE
EACCES: permission denied, unlink .... eslintrc.json

### ISSUE THREAD

**Issue by alznyc** [TryGhost/Ghost-CLI#661]
**Issue Summary**
Recently, after running ghost update after 1.20, the updater will give the following message:

Message: 'EACCES: permission denied, unlink '/var/www/XXXX/versions/1.19.0/.eslintrc.json''

Debug Information:
OS: Ubuntu, v16.04
Node Version: v6.9.1
Ghost-CLI Version: 1.5.2
Environment: production
Command: 'ghost update'

However, the actual update completed and everything works fine (the version is correct in ghost admin). Ghost doctor yields nothing negative. Most likely nothing to worry about, but concerned it may compound into something later?

Technical details:
Ghost Version: current
Browser/OS: Ubuntu 16.04.3 LTS
Database: MYSQL

**Comment by AileenCGN** [comment]
This issue seems to happen when older versions where installed with a different user than the one that is used now. Can you confirm this, @alznyc?

Workaround for this is to either change the permissions of the `/versions` directory to the correct user (the one that owns the install directory) with `sudo chown <user>:<user> /var/www/ghost/versions -R` and try again.

I added this to the [troubleshooting guide](https://docs.ghost.org/v1/docs/troubleshooting#section-eacces-permission-denied-unlink-var-www-ghost-versions-1-19-0-eslintrc-json-).

I will close this for now, but leave a note in our existing Ghost doctor improvements issue #47

**Comment by dosconcombres** [comment]
With DigitalOcean's One-Click install the application install folder is /var/www/ghost. It doesn't seem that permissions for CLI management are included by default. 

I solved this sticking point by giving permissions to the ghost-mgr, which is the CLI user, I guess. It didn't work with other users I thought had permission.

`sudo chown ghost-mgr:ghost-mgr /var/www/ghost`
`ghost update`
