### ISSUE TITLE
Use the https URL if the user had set up SSL

### ISSUE THREAD

**Issue by meteorpublish** [TryGhost/Ghost-CLI#666]
## This issue is a

* [x] Feature Request
* [ ] Bug Report

### Summary

After completing `ghost install` with SSL, my blog URL was displayed as http://...

### Steps to Reproduce (for a bug report)

1. Complete the [production install steps](https://docs.ghost.org/docs/install)
2. Make sure to set up SSL

### Log file (for a bug report)

```
✔ Starting Ghost
You can access your blog at http://myblog.com/
```

### Technical details (for a bug report)

    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost install'

**Comment by acburdine** [comment]
@meteorpublish The url that's displayed is taken directly from the config - so if you used the http version of your url whenever Ghost-CLI prompted for a URL, then it will display the http url on start, even if you set up SSL. If you want the https url to be shown, then you'll need to configure it as such 😉 

Going to close this as the current behavior is intentional.

**Comment by meteorpublish** [comment]
Yeah, technically that's correct. User entered "http", direct them to "http". But,

1. Do we want to promote security? If so, we should direct the user to the https:// URL if SSL was set up.

2. Do we want to be strict? If so, HTTP. Or do we want to be user-friendly? HTTPS makes more sense then because if a user has set up SSL, the second thing they want to do is check that SSL works.
