### ISSUE TITLE
Using Ghost-CLI programatically

### ISSUE THREAD

**Issue by flip111** [TryGhost/Ghost-CLI#721]
Following the steps in this guide https://docs.ghost.org/docs/using-ghost-cli-programatically

i get an error:

```
Running sudo command: useradd --system --user-group ghost
☱ /usr/lib/node_modules/ghost-cli/lib/ui/index.js:123
            throw new errors.SystemError('Prompts have been disabled, please provide options via command line flags');
            ^

Error: Prompts have been disabled, please provide options via command line flags
    at UI.prompt (/usr/lib/node_modules/ghost-cli/lib/ui/index.js:123:19)
    at Socket.cp.stderr.on (/usr/lib/node_modules/ghost-cli/lib/ui/index.js:202:22)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
```

From: https://github.com/TryGhost/Ghost/issues/9629

**Comment by AileenCGN** [comment]
@flip111 In the issue template that you deleted when you opened this issue, we asked you for additional info, such as **OS**, current **Ghost-CLI version**, **Ghost version**, potential log files etc.

Please share this information as well as steps to reproduce, otherwise we're not able to debug this possible issue.

**Comment by flip111** [comment]
OS: Ubuntu, v16.04
Node Version: v8.11.1
Ghost-CLI Version: 1.7.3
Ghost version: current (yesterday)

Steps to reproduce: https://docs.ghost.org/docs/using-ghost-cli-programatically

What log file would you like to see?

**Comment by AileenCGN** [comment]
> Steps to reproduce: https://docs.ghost.org/docs/using-ghost-cli-programatically

Posting the link again still doesn't tell me the steps you did, as there are multiple steps described.

**Comment by vikaspotluri123** [comment]
You're running into this error because you need to use sudo to create a user; the CLI has to prompt you for your sudo password, but since you said no prompting, it is stuck so it throws this error and exits.

**Comment by acburdine** [comment]
@flip111 So this is a bit of a tricky issue - in order to work in programmatic mode, you need to do one of two things:

- run the entire ghost-cli command as sudo (easiest solution, but presents a potential security issue) OR
- run ghost-cli with a user that can use passwordless sudo (see instructions on how to do that [here](https://serverfault.com/questions/160581/how-to-setup-passwordless-sudo-on-linux))

This isn't something that we can really "fix" in the CLI, but the docs on programmatic usage should definitely be updated to include the part about sudo - I'll work on doing that.

**Comment by flip111** [comment]
Hi @acburdine thanks for your understanding. Which one of the two options do you recommend? I'm not sure which one is best in my situation. I'm fine with both.

**Comment by acburdine** [comment]
@flip111 definitely the second approach - that way the things the CLI does with sudo permissions are still limited to specific commands 😄

**Comment by AileenCGN** [comment]
The docs for this are updated and include a big warning with instructions on how to set up the Ghost CLI user to run `sudo` passwordless: https://docs.ghost.org/v1/docs/using-ghost-cli-programatically

**Comment by flip111** [comment]
The documentation says now `<user> ALL=(ALL) NOPASSWD: ALL`. Which are the same privileges as running the ghost-cli as root, so there is not added benefit with this.

I thought i was suppose to execute the `ghost install` command with the same user that ghost is running under normally. But now i see this is not the case (this was not clear to me before). So i will just use sudo then ..

**Comment by flip111** [comment]
Also i think the `--start` should be removed from the documentation in how to setup ghost programatically. It makes no sense to start ghost with either root or a special user with sudo privileges.

This error
```
Can't run command as 'root' user.
Please use the user you set up in the installation process, or create a new user with regular account privileges and use this user to run 'ghost install'.
See https://docs.ghost.org/docs/install#section-create-a-new-user for more information
```

Was actually the reason i believed before i had to use the same user for the installation as well as running ghost. Now i'm still not sure if this is the case or not. What does `regular account privileges` even mean? I don't think `sudo` are regular account privileges. So the advice to create a user with regular privileges to run `ghost install` is wrong.

I like this ticket to be re-opened.

**Comment by flip111** [comment]
So as i understand, i need to:

1. create a new user with the same privileges as root (according to documentation as it is now) - because the ghost install does not permit running as root.
2. run ghost install with this user
3. remove this user (because i don't need it)
4. create a regular user to run ghost
5. run ghost

Maybe just remove the check to run ghost install as root as simplify the first 3 steps

**Comment by acburdine** [comment]
@flip111 apologies for the delayed response - been a bit busy as of late. The reason Ghost-CLI doesn't permit running an installation as root (and why it's still better to create a passwordless sudo user) is that even though Ghost-CLI can (with passwordless sudo) execute anything it wants, it explicitly limits the usage of sudo to specific commands within the setup process itself - e.g. running `sudo systemctl start ghost_<service>`. This is to a degree safer, because none of the _ghost-cli_ code specifically has sudo-level permissions, meaning any bugs that happen are less likely to have a dangerous effect.

**Comment by flip111** [comment]
> it explicitly limits the usage of sudo to specific commands within the setup process itself

I understand this sentence but i don't understand why this is the case, do you have some background information on it?

> Also i think the --start should be removed from the documentation in how to setup ghost programatically. It makes no sense to start ghost with either root or a special user with sudo privileges.

I like this ticket to be reopened just for this.

**Comment by mcgoosh** [comment]
@flip111 
I can confirm the second solution worked for me.

**Comment by yamsellem** [comment]
For anyone coming here, I've struggled several hours to use the `--no-prompt` flag.
As of ghost-cli `1.17.3` (and ghost `4.9.4`) here are the sudoers edits needed:

```
echo 'xxx ALL=(ALL) NOPASSWD: /bin/chown -R ghost\:ghost /var/www/ghost/*' | sudo EDITOR='tee -a' visudo
echo 'xxx ALL=(ALL) NOPASSWD: /bin/mv /lib/systemd/system' | sudo EDITOR='tee -a' visudo
echo 'xxx ALL=(ALL) NOPASSWD: /bin/systemctl * ghost*' | sudo EDITOR='tee -a' visudo
```

And the full install command:

```
sudo -u xxx ghost install $GHOST_VERSION --no-prompt --url https://yoursite --db mysql --dbhost localhost --dbuser root --dbpass password --dbname ghost_prod --process systemd --no-setup-nginx --no-setup-ssl
```

Where `xxx` is the dedicated user dedicated to ghost command (xxx != ghost).

IMO this should be documented (or I've missed something) in [the ghost-cli page](https://ghost.org/docs/ghost-cli/#ghost-install).
