### ISSUE TITLE
Unable to use special characters in config 

### ISSUE THREAD

**Issue by prashanthmadi** [TryGhost/Ghost-CLI#838]
special characters in config not working as expected

### Steps to Reproduce

```
ghost config --dbpass sea123$$
```
### Log file

config.json has below content after running above command.. its giving  15195 instead of $$ as below
```
      "password": "sea12315195",
```

This causes my migrate task fails as the password is wrong

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: MAC OS X
* Node Version: 8.12
* Ghost-CLI version: 1.9.6
* Ghost version: 2.2.0 (at ~/workspace/ghosttest)
* Environment: dev
* Command: ghost config

**Comment by prashanthmadi** [comment]
works with @ but fails with $ .. looks like only works for few special characters.

**Comment by acburdine** [comment]
@prashanthmadi this isn't an issue with Ghost-CLI, this is because `$` is a special character in Bash.

If you are using any special characters (non-alphanumeric), I suggest that you wrap them in quotes like so: `ghost config --dbpass 'mypassword$with$special@chars'`. If you do that, the special characters will be respected and you won't get weird behavior.

Going to close this as it isn't a CLI issue. If you're still having trouble after following my idea above, let me know and we can reopen this if it _is_ an actual issue.

**Comment by prashanthmadi** [comment]
thanks @acburdine .

I tried with double quote before that had issue too but using single quote seems to work..

**Comment by acburdine** [comment]
That makes sense - as double quotes still expand special characters. Single quotes is the way to go, glad you got it working 😅
