### ISSUE TITLE
ghost install --v1 seems to try installing v2

### ISSUE THREAD

**Issue by squarewave24** [TryGhost/Ghost-CLI#874]
when i run this: 

`ghost install --v1`

i get this error 

> ✔ Checking MySQL is installed
> ✔ Checking for latest Ghost version
> ✔ Setting up install directory
> ✖ Downloading and installing Ghost v2.13.1
> A SystemError occurred.
> Message: Ghost v2.13.1 is not compatible with this version of the CLI.

```
$ ghost -v
Ghost-CLI version: 1.4.2

```

**Comment by acburdine** [comment]
@squarewave24 the reason you're seeing that issue is you're running a fairly outdated version of Ghost-CLI. The `--v1` flag was added in Ghost-CLI version 1.9.0, so you will need to either upgrade to that version of Ghost-CLI, or run something like `ghost install v1.25.5` to install the latest version of Ghost 1.x.

Going to close this as there's not an issue with Ghost-CLI here.
