### ISSUE TITLE
Support for Debian 9

### ISSUE THREAD

**Issue by javidotpro** [TryGhost/Ghost-CLI#979]
### Summary

At the moment the CLI script it's design for Ubuntu 16.04/18.04 which is based on Debian, any chance we can support Debian 9 for the CLI too please?

**Comment by acburdine** [comment]
@javidotpro as described in the [README](https://github.com/TryGhost/Ghost-CLI#recommended-stack), the reason we only support Ubuntu 16/18 is because it drastically reduces the maintenance overhead that would be required by supporting multiple stacks.

That said, Debian & Ubuntu are similar enough that you can _probably_ get by with adding the `--no-stack` flag to `ghost install` (see the docs [here](https://docs.ghost.org/api/ghost-cli/install/)). No guarantees that everything will work though.

Going to close this issue as the reasoning behind supporting only ubuntu at present is listed in the README.
